/**
 * BG3SE-macOS - IDE Type Helper Generation
 *
 * Generates LuaLS-compatible type annotation files for VS Code IntelliSense.
 */

#include "lua_ide_helpers.h"
#include "version.h"
#include "logging.h"
#include "../entity/component_registry.h"
#include "../entity/component_property.h"
#include "../enum/enum_registry.h"

#include <lua.h>
#include <lauxlib.h>
#include <stdio.h>
#include <string.h>

// ============================================================================
// Field Type to LuaLS Type Mapping
// ============================================================================

static const char* field_type_to_lua_type(FieldType type) {
    switch (type) {
        case FIELD_TYPE_INT8:
        case FIELD_TYPE_UINT8:
        case FIELD_TYPE_INT16:
        case FIELD_TYPE_UINT16:
        case FIELD_TYPE_INT32:
        case FIELD_TYPE_UINT32:
        case FIELD_TYPE_INT64:
        case FIELD_TYPE_UINT64:
            return "integer";
        case FIELD_TYPE_BOOL:
            return "boolean";
        case FIELD_TYPE_FLOAT:
        case FIELD_TYPE_DOUBLE:
            return "number";
        case FIELD_TYPE_FIXEDSTRING:
        case FIELD_TYPE_GUID:
            return "string";
        case FIELD_TYPE_ENTITY_HANDLE:
            return "EntityHandle";
        case FIELD_TYPE_VEC3:
            return "vec3";
        case FIELD_TYPE_VEC4:
            return "vec4";
        case FIELD_TYPE_INT32_ARRAY:
            return "integer[]";
        case FIELD_TYPE_FLOAT_ARRAY:
            return "number[]";
        case FIELD_TYPE_DYNAMIC_ARRAY:
            return "table";
        default:
            return "any";
    }
}

// ============================================================================
// Section Emitters
// ============================================================================

static void emit_header(luaL_Buffer *buf) {
    luaL_addstring(buf, "---@meta\n");
    luaL_addstring(buf, "---@diagnostic disable\n");
    luaL_addstring(buf, "\n");
    luaL_addstring(buf, "-- BG3SE-macOS IDE Type Definitions\n");
    luaL_addstring(buf, "-- Generated by Ext.Types.GenerateIdeHelpers()\n");
    luaL_addstring(buf, "-- For LuaLS / VS Code IntelliSense\n");
    luaL_addstring(buf, "\n");
}

static void emit_basic_types(luaL_Buffer *buf) {
    luaL_addstring(buf, "--#region Basic Types\n\n");
    luaL_addstring(buf, "---@class EntityHandle\n");
    luaL_addstring(buf, "---@field TypeId integer\n");
    luaL_addstring(buf, "---@field Type string\n");
    luaL_addstring(buf, "---@field Salt integer\n");
    luaL_addstring(buf, "---@field Index integer\n");
    luaL_addstring(buf, "\n");
    luaL_addstring(buf, "---@alias vec3 number[]\n");
    luaL_addstring(buf, "---@alias vec4 number[]\n");
    luaL_addstring(buf, "---@alias mat3 number[]\n");
    luaL_addstring(buf, "---@alias mat4 number[]\n");
    luaL_addstring(buf, "\n");
    luaL_addstring(buf, "--#endregion\n\n");
}

static int emit_enums(luaL_Buffer *buf) {
    luaL_addstring(buf, "--#region Enums\n\n");

    int enum_count = enum_registry_get_count();
    for (int i = 0; i < enum_count; i++) {
        EnumTypeInfo *einfo = enum_registry_get(i);
        if (!einfo || !einfo->name) continue;

        char line[4096];
        snprintf(line, sizeof(line), "---@alias %s", einfo->name);
        luaL_addstring(buf, line);

        for (int j = 0; j < einfo->value_count; j++) {
            snprintf(line, sizeof(line), "%s\"%s\"",
                     j == 0 ? " " : "|",
                     einfo->values[j].label);
            luaL_addstring(buf, line);
        }
        luaL_addstring(buf, "\n");
    }
    luaL_addstring(buf, "\n--#endregion\n\n");
    return enum_count;
}

static int emit_components(luaL_Buffer *buf) {
    luaL_addstring(buf, "--#region Components\n\n");

    // Components with layouts (have property definitions)
    int layout_count = component_property_get_layout_count();
    for (int i = 0; i < layout_count; i++) {
        const ComponentLayoutDef *layout = component_property_get_layout_at(i);
        if (!layout || !layout->componentName) continue;

        char line[1024];
        snprintf(line, sizeof(line), "---@class %s\n", layout->componentName);
        luaL_addstring(buf, line);

        for (int j = 0; j < layout->propertyCount; j++) {
            const ComponentPropertyDef *prop = &layout->properties[j];
            const char *lua_type = field_type_to_lua_type(prop->type);

            if (prop->readOnly) {
                snprintf(line, sizeof(line), "---@field %s %s @readonly\n",
                         prop->name, lua_type);
            } else {
                snprintf(line, sizeof(line), "---@field %s %s\n",
                         prop->name, lua_type);
            }
            luaL_addstring(buf, line);
        }
        luaL_addstring(buf, "\n");
    }

    // Stub classes for components without layouts
    int comp_count = component_registry_count();
    for (int i = 0; i < comp_count; i++) {
        const ComponentInfo *cinfo = component_registry_get_at(i);
        if (!cinfo || !cinfo->name) continue;

        const ComponentLayoutDef *layout = component_property_get_layout(cinfo->name);
        if (layout) continue;  // Already emitted above

        char line[1024];
        snprintf(line, sizeof(line), "---@class %s\n\n", cinfo->name);
        luaL_addstring(buf, line);
    }

    luaL_addstring(buf, "--#endregion\n\n");
    return layout_count;
}

static void emit_ext_namespace(luaL_Buffer *buf) {
    luaL_addstring(buf, "--#region Ext Namespace\n\n");

    // Sub-namespaces
    luaL_addstring(buf, "---@class Ext_Entity\n");
    luaL_addstring(buf, "---@field Get fun(guid: string): EntityHandle? Get entity by GUID\n");
    luaL_addstring(buf, "---@field GetByHandle fun(handle: EntityHandle): EntityHandle? Get entity by handle\n");
    luaL_addstring(buf, "---@field GetComponent fun(entity: EntityHandle, name: string): table? Get component from entity\n");
    luaL_addstring(buf, "\n");

    luaL_addstring(buf, "---@class Ext_Stats\n");
    luaL_addstring(buf, "---@field Get fun(name: string): table? Get stat object by name\n");
    luaL_addstring(buf, "---@field GetAll fun(type?: string): string[] Get all stat names\n");
    luaL_addstring(buf, "---@field Create fun(name: string, type: string, template?: string): table Create new stat\n");
    luaL_addstring(buf, "---@field Sync fun(name: string, persist?: boolean) Sync stat to clients\n");
    luaL_addstring(buf, "\n");

    luaL_addstring(buf, "---@class Ext_Osiris\n");
    luaL_addstring(buf, "---@field RegisterListener fun(name: string, arity: integer, event: string, callback: function) Register Osiris listener\n");
    luaL_addstring(buf, "---@field NewCall fun(name: string, params: string) Create custom Osiris call\n");
    luaL_addstring(buf, "---@field NewQuery fun(name: string, params: string) Create custom Osiris query\n");
    luaL_addstring(buf, "---@field NewEvent fun(name: string, params: string) Create custom Osiris event\n");
    luaL_addstring(buf, "\n");

    luaL_addstring(buf, "---@class Ext_Events\n");
    luaL_addstring(buf, "---@field Subscribe fun(event: string, callback: function, priority?: integer) Subscribe to event\n");
    luaL_addstring(buf, "---@field Unsubscribe fun(handle: integer) Unsubscribe from event\n");
    luaL_addstring(buf, "\n");

    luaL_addstring(buf, "---@class Ext_Timer\n");
    luaL_addstring(buf, "---@field WaitFor fun(ms: number, callback: function): integer Create timer\n");
    luaL_addstring(buf, "---@field WaitForRealtime fun(ms: number, callback: function): integer Create realtime timer\n");
    luaL_addstring(buf, "---@field Cancel fun(handle: integer) Cancel timer\n");
    luaL_addstring(buf, "---@field Pause fun(handle: integer) Pause timer\n");
    luaL_addstring(buf, "---@field Resume fun(handle: integer) Resume timer\n");
    luaL_addstring(buf, "\n");

    luaL_addstring(buf, "---@class Ext_Types\n");
    luaL_addstring(buf, "---@field GetAllTypes fun(): string[] Get all type names\n");
    luaL_addstring(buf, "---@field GetTypeInfo fun(name: string): table Get type info\n");
    luaL_addstring(buf, "---@field TypeOf fun(obj: any): table? Get type info for object\n");
    luaL_addstring(buf, "---@field IsA fun(obj: any, type: string): boolean Type check\n");
    luaL_addstring(buf, "---@field GetComponentLayout fun(name: string): table? Get component layout\n");
    luaL_addstring(buf, "---@field GetAllLayouts fun(): string[] Get all layout names\n");
    luaL_addstring(buf, "---@field GenerateIdeHelpers fun(filename?: string): string Generate IDE helpers\n");
    luaL_addstring(buf, "\n");

    luaL_addstring(buf, "---@class Ext_IO\n");
    luaL_addstring(buf, "---@field LoadFile fun(path: string): string?, string? Load file contents\n");
    luaL_addstring(buf, "---@field SaveFile fun(path: string, content: string): boolean Save file\n");
    luaL_addstring(buf, "\n");

    luaL_addstring(buf, "---@class Ext_Vars\n");
    luaL_addstring(buf, "---@field GetModVariables fun(modGuid: string): table Get mod variables\n");
    luaL_addstring(buf, "\n");

    luaL_addstring(buf, "---@class Ext_Math\n");
    luaL_addstring(buf, "---@field Add fun(a: vec3|vec4, b: vec3|vec4): vec3|vec4 Add vectors\n");
    luaL_addstring(buf, "---@field Sub fun(a: vec3|vec4, b: vec3|vec4): vec3|vec4 Subtract vectors\n");
    luaL_addstring(buf, "---@field Mul fun(a: vec3|vec4, b: number): vec3|vec4 Multiply by scalar\n");
    luaL_addstring(buf, "---@field Dot fun(a: vec3|vec4, b: vec3|vec4): number Dot product\n");
    luaL_addstring(buf, "---@field Cross fun(a: vec3, b: vec3): vec3 Cross product\n");
    luaL_addstring(buf, "---@field Length fun(v: vec3|vec4): number Vector length\n");
    luaL_addstring(buf, "---@field Normalize fun(v: vec3|vec4): vec3|vec4 Normalize vector\n");
    luaL_addstring(buf, "\n");

    // Main Ext class
    luaL_addstring(buf, "---@class Ext\n");
    luaL_addstring(buf, "---@field Entity Ext_Entity\n");
    luaL_addstring(buf, "---@field Stats Ext_Stats\n");
    luaL_addstring(buf, "---@field Osiris Ext_Osiris\n");
    luaL_addstring(buf, "---@field Events Ext_Events\n");
    luaL_addstring(buf, "---@field Timer Ext_Timer\n");
    luaL_addstring(buf, "---@field Types Ext_Types\n");
    luaL_addstring(buf, "---@field IO Ext_IO\n");
    luaL_addstring(buf, "---@field Vars Ext_Vars\n");
    luaL_addstring(buf, "---@field Math Ext_Math\n");
    luaL_addstring(buf, "---@field Print fun(...) Print to console\n");
    luaL_addstring(buf, "---@field GetVersion fun(): string Get BG3SE version\n");
    luaL_addstring(buf, "---@field IsServer fun(): boolean Check if server context\n");
    luaL_addstring(buf, "---@field IsClient fun(): boolean Check if client context\n");
    luaL_addstring(buf, "---@field GetContext fun(): string Get current context\n");
    luaL_addstring(buf, "Ext = {}\n\n");

    // Osi namespace stub
    luaL_addstring(buf, "---@class Osi\n");
    luaL_addstring(buf, "---@field [string] fun(...): any Osiris function call\n");
    luaL_addstring(buf, "Osi = {}\n\n");

    // Mods global
    luaL_addstring(buf, "---@type table<string, table>\n");
    luaL_addstring(buf, "Mods = {}\n\n");

    luaL_addstring(buf, "--#endregion\n");
}

// ============================================================================
// Public API
// ============================================================================

int lua_ide_helpers_generate(lua_State *L) {
    const char *filename = luaL_optstring(L, 1, NULL);

    luaL_Buffer buf;
    luaL_buffinit(L, &buf);

    // Emit sections
    emit_header(&buf);
    emit_basic_types(&buf);
    int enum_count = emit_enums(&buf);
    int layout_count = emit_components(&buf);
    emit_ext_namespace(&buf);

    // Finalize buffer
    luaL_pushresult(&buf);

    // Optionally save to file
    if (filename) {
        const char *content = lua_tostring(L, -1);
        char path[512];
        snprintf(path, sizeof(path), "%s/%s", bg3se_get_data_dir(), filename);

        FILE *f = fopen(path, "w");
        if (f) {
            fputs(content, f);
            fclose(f);
            LOG_LUA_INFO("Generated IDE helpers: %s (%d layouts, %d enums)",
                       path, layout_count, enum_count);
        } else {
            LOG_LUA_INFO("Failed to write IDE helpers to: %s", path);
        }
    }

    return 1;  // Return the content string
}
