// Auto-generated ls:: component layouts
// Generated by cross-referencing:
// - Windows BG3SE headers: /Users/tomdimino/Desktop/Programming/bg3se/BG3Extender/GameDefinitions/Components/
// - Ghidra ARM64 sizes: /Users/tomdimino/Desktop/Programming/bg3se-macos/ghidra/offsets/components/COMPONENT_SIZES_LS*.md
//
// Total: 45 component layouts

// ============================================================================
// Tag Components (1 byte, no fields)
// ============================================================================

// ls::AlwaysUpdateEffectComponent - 1 bytes (0x01)
// Source: COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_AlwaysUpdateEffect_Properties[] = {};
static const ComponentLayoutDef g_ls_AlwaysUpdateEffect_Layout = {
    .componentName = "ls::AlwaysUpdateEffectComponent",
    .shortName = "AlwaysUpdateEffect",
    .componentTypeIndex = 0,
    .componentSize = 0x01,
    .properties = g_ls_AlwaysUpdateEffect_Properties,
    .propertyCount = 0,
};

// ls::AnimationUpdateComponent - 1 bytes (0x01)
// Source: Visual.h, COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_AnimationUpdate_Properties[] = {};
static const ComponentLayoutDef g_ls_AnimationUpdate_Layout = {
    .componentName = "ls::AnimationUpdateComponent",
    .shortName = "AnimationUpdate",
    .componentTypeIndex = 0,
    .componentSize = 0x01,
    .properties = g_ls_AnimationUpdate_Properties,
    .propertyCount = 0,
};

// ls::ClusterAttachRequestComponent - 1 bytes (0x01)
// Source: COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_ClusterAttachRequest_Properties[] = {};
static const ComponentLayoutDef g_ls_ClusterAttachRequest_Layout = {
    .componentName = "ls::ClusterAttachRequestComponent",
    .shortName = "ClusterAttachRequest",
    .componentTypeIndex = 0,
    .componentSize = 0x01,
    .properties = g_ls_ClusterAttachRequest_Properties,
    .propertyCount = 0,
};

// ls::ClusterComponent - 1 bytes (0x01)
// Source: COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_Cluster_Properties[] = {};
static const ComponentLayoutDef g_ls_Cluster_Layout = {
    .componentName = "ls::ClusterComponent",
    .shortName = "Cluster",
    .componentTypeIndex = 0,
    .componentSize = 0x01,
    .properties = g_ls_Cluster_Properties,
    .propertyCount = 0,
};

// ls::EffectCreateOneFrameComponent - 1 bytes (0x01)
// Source: COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_EffectCreateOneFrame_Properties[] = {};
static const ComponentLayoutDef g_ls_EffectCreateOneFrame_Layout = {
    .componentName = "ls::EffectCreateOneFrameComponent",
    .shortName = "EffectCreateOneFrame",
    .componentTypeIndex = 0,
    .componentSize = 0x01,
    .properties = g_ls_EffectCreateOneFrame_Properties,
    .propertyCount = 0,
};

// ls::IsGlobalComponent - 1 bytes (0x01)
// Source: COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_IsGlobal_Properties[] = {};
static const ComponentLayoutDef g_ls_IsGlobal_Layout = {
    .componentName = "ls::IsGlobalComponent",
    .shortName = "IsGlobal",
    .componentTypeIndex = 0,
    .componentSize = 0x01,
    .properties = g_ls_IsGlobal_Properties,
    .propertyCount = 0,
};

// ls::LevelInstanceLoadComponent - 1 bytes (0x01)
// Source: COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_LevelInstanceLoad_Properties[] = {};
static const ComponentLayoutDef g_ls_LevelInstanceLoad_Layout = {
    .componentName = "ls::LevelInstanceLoadComponent",
    .shortName = "LevelInstanceLoad",
    .componentTypeIndex = 0,
    .componentSize = 0x01,
    .properties = g_ls_LevelInstanceLoad_Properties,
    .propertyCount = 0,
};

// ls::LevelIsOwnerComponent - 1 bytes (0x01)
// Source: Components.h, COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_LevelIsOwner_Properties[] = {};
static const ComponentLayoutDef g_ls_LevelIsOwner_Layout = {
    .componentName = "ls::LevelIsOwnerComponent",
    .shortName = "LevelIsOwner",
    .componentTypeIndex = 0,
    .componentSize = 0x01,
    .properties = g_ls_LevelIsOwner_Properties,
    .propertyCount = 0,
};

// ls::PhysicsLoadedComponent - 1 bytes (0x01)
// Source: COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_PhysicsLoaded_Properties[] = {};
static const ComponentLayoutDef g_ls_PhysicsLoaded_Layout = {
    .componentName = "ls::PhysicsLoadedComponent",
    .shortName = "PhysicsLoaded",
    .componentTypeIndex = 0,
    .componentSize = 0x01,
    .properties = g_ls_PhysicsLoaded_Properties,
    .propertyCount = 0,
};

// ls::PhysicsStreamLoadComponent - 1 bytes (0x01)
// Source: COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_PhysicsStreamLoad_Properties[] = {};
static const ComponentLayoutDef g_ls_PhysicsStreamLoad_Layout = {
    .componentName = "ls::PhysicsStreamLoadComponent",
    .shortName = "PhysicsStreamLoad",
    .componentTypeIndex = 0,
    .componentSize = 0x01,
    .properties = g_ls_PhysicsStreamLoad_Properties,
    .propertyCount = 0,
};

// ls::RoomTriggerTagComponent - 1 bytes (0x01)
// Source: COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_RoomTriggerTag_Properties[] = {};
static const ComponentLayoutDef g_ls_RoomTriggerTag_Layout = {
    .componentName = "ls::RoomTriggerTagComponent",
    .shortName = "RoomTriggerTag",
    .componentTypeIndex = 0,
    .componentSize = 0x01,
    .properties = g_ls_RoomTriggerTag_Properties,
    .propertyCount = 0,
};

// ls::SavegameComponent - 1 bytes (0x01)
// Source: COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_Savegame_Properties[] = {};
static const ComponentLayoutDef g_ls_Savegame_Layout = {
    .componentName = "ls::SavegameComponent",
    .shortName = "Savegame",
    .componentTypeIndex = 0,
    .componentSize = 0x01,
    .properties = g_ls_Savegame_Properties,
    .propertyCount = 0,
};

// ls::SoundActivatedComponent - 1 bytes (0x1)
// Source: COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_SoundActivated_Properties[] = {};
static const ComponentLayoutDef g_ls_SoundActivated_Layout = {
    .componentName = "ls::SoundActivatedComponent",
    .shortName = "SoundActivated",
    .componentTypeIndex = 0,
    .componentSize = 0x01,
    .properties = g_ls_SoundActivated_Properties,
    .propertyCount = 0,
};

// ls::VisualChangedEventOneFrameComponent - 1 bytes (0x01)
// Source: COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_VisualChangedEventOneFrame_Properties[] = {};
static const ComponentLayoutDef g_ls_VisualChangedEventOneFrame_Layout = {
    .componentName = "ls::VisualChangedEventOneFrameComponent",
    .shortName = "VisualChangedEventOneFrame",
    .componentTypeIndex = 0,
    .componentSize = 0x01,
    .properties = g_ls_VisualChangedEventOneFrame_Properties,
    .propertyCount = 0,
};

// ls::VisualLoadedComponent - 1 bytes (0x01)
// Source: COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_VisualLoaded_Properties[] = {};
static const ComponentLayoutDef g_ls_VisualLoaded_Layout = {
    .componentName = "ls::VisualLoadedComponent",
    .shortName = "VisualLoaded",
    .componentTypeIndex = 0,
    .componentSize = 0x01,
    .properties = g_ls_VisualLoaded_Properties,
    .propertyCount = 0,
};

// ls::animation::AnimationSetUpdateRequestComponent - 1 bytes (0x01)
// Source: Visual.h, COMPONENT_SIZES_LS_ANIMATION.md
static const ComponentPropertyDef g_ls_AnimationSetUpdateRequest_Properties[] = {};
static const ComponentLayoutDef g_ls_AnimationSetUpdateRequest_Layout = {
    .componentName = "ls::animation::AnimationSetUpdateRequestComponent",
    .shortName = "AnimationSetUpdateRequest",
    .componentTypeIndex = 0,
    .componentSize = 0x01,
    .properties = g_ls_AnimationSetUpdateRequest_Properties,
    .propertyCount = 0,
};

// ============================================================================
// Simple Primitive Components (2-8 bytes)
// ============================================================================

// ls::CullComponent - 2 bytes (0x02)
// Source: COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_Cull_Properties[] = {
    { "Flags", 0x00, FIELD_TYPE_UINT8, 0, true },
    { "Flags2", 0x01, FIELD_TYPE_UINT8, 0, true },
};
static const ComponentLayoutDef g_ls_Cull_Layout = {
    .componentName = "ls::CullComponent",
    .shortName = "Cull",
    .componentTypeIndex = 0,
    .componentSize = 0x02,
    .properties = g_ls_Cull_Properties,
    .propertyCount = sizeof(g_ls_Cull_Properties) / sizeof(g_ls_Cull_Properties[0]),
};

// ls::TimeFactorComponent - 4 bytes (0x04)
// Source: Components.h, COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_TimeFactor_Properties[] = {
    { "Value", 0x00, FIELD_TYPE_FLOAT, 0, true },
};
static const ComponentLayoutDef g_ls_TimeFactor_Layout = {
    .componentName = "ls::TimeFactorComponent",
    .shortName = "TimeFactor",
    .componentTypeIndex = 0,
    .componentSize = 0x04,
    .properties = g_ls_TimeFactor_Properties,
    .propertyCount = sizeof(g_ls_TimeFactor_Properties) / sizeof(g_ls_TimeFactor_Properties[0]),
};

// ls::LevelRootComponent - 4 bytes (0x04)
// Source: Components.h, COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_LevelRoot_Properties[] = {
    { "LevelName", 0x00, FIELD_TYPE_FIXEDSTRING, 0, true },
};
static const ComponentLayoutDef g_ls_LevelRoot_Layout = {
    .componentName = "ls::LevelRootComponent",
    .shortName = "LevelRoot",
    .componentTypeIndex = 0,
    .componentSize = 0x04,
    .properties = g_ls_LevelRoot_Properties,
    .propertyCount = sizeof(g_ls_LevelRoot_Properties) / sizeof(g_ls_LevelRoot_Properties[0]),
};

// ls::LevelUnloadedOneFrameComponent - 4 bytes (0x04)
// Source: Components.h, COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_LevelUnloadedOneFrame_Properties[] = {
    { "Level", 0x00, FIELD_TYPE_FIXEDSTRING, 0, true },
};
static const ComponentLayoutDef g_ls_LevelUnloadedOneFrame_Layout = {
    .componentName = "ls::LevelUnloadedOneFrameComponent",
    .shortName = "LevelUnloadedOneFrame",
    .componentTypeIndex = 0,
    .componentSize = 0x04,
    .properties = g_ls_LevelUnloadedOneFrame_Properties,
    .propertyCount = sizeof(g_ls_LevelUnloadedOneFrame_Properties) / sizeof(g_ls_LevelUnloadedOneFrame_Properties[0]),
};

// ls::ClusterBoundMaxComponent - 4 bytes (0x04)
// Source: COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_ClusterBoundMax_Properties[] = {
    { "Value", 0x00, FIELD_TYPE_FLOAT, 0, true },
};
static const ComponentLayoutDef g_ls_ClusterBoundMax_Layout = {
    .componentName = "ls::ClusterBoundMaxComponent",
    .shortName = "ClusterBoundMax",
    .componentTypeIndex = 0,
    .componentSize = 0x04,
    .properties = g_ls_ClusterBoundMax_Properties,
    .propertyCount = sizeof(g_ls_ClusterBoundMax_Properties) / sizeof(g_ls_ClusterBoundMax_Properties[0]),
};

// ls::ClusterDistMaxComponent - 4 bytes (0x04)
// Source: COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_ClusterDistMax_Properties[] = {
    { "Value", 0x00, FIELD_TYPE_FLOAT, 0, true },
};
static const ComponentLayoutDef g_ls_ClusterDistMax_Layout = {
    .componentName = "ls::ClusterDistMaxComponent",
    .shortName = "ClusterDistMax",
    .componentTypeIndex = 0,
    .componentSize = 0x04,
    .properties = g_ls_ClusterDistMax_Properties,
    .propertyCount = sizeof(g_ls_ClusterDistMax_Properties) / sizeof(g_ls_ClusterDistMax_Properties[0]),
};

// ls::ClusterDistMinComponent - 4 bytes (0x04)
// Source: COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_ClusterDistMin_Properties[] = {
    { "Value", 0x00, FIELD_TYPE_FLOAT, 0, true },
};
static const ComponentLayoutDef g_ls_ClusterDistMin_Layout = {
    .componentName = "ls::ClusterDistMinComponent",
    .shortName = "ClusterDistMin",
    .componentTypeIndex = 0,
    .componentSize = 0x04,
    .properties = g_ls_ClusterDistMin_Properties,
    .propertyCount = sizeof(g_ls_ClusterDistMin_Properties) / sizeof(g_ls_ClusterDistMin_Properties[0]),
};

// ls::ClusterPositionXComponent - 4 bytes (0x04)
// Source: COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_ClusterPositionX_Properties[] = {
    { "Value", 0x00, FIELD_TYPE_FLOAT, 0, true },
};
static const ComponentLayoutDef g_ls_ClusterPositionX_Layout = {
    .componentName = "ls::ClusterPositionXComponent",
    .shortName = "ClusterPositionX",
    .componentTypeIndex = 0,
    .componentSize = 0x04,
    .properties = g_ls_ClusterPositionX_Properties,
    .propertyCount = sizeof(g_ls_ClusterPositionX_Properties) / sizeof(g_ls_ClusterPositionX_Properties[0]),
};

// ls::ClusterPositionYComponent - 4 bytes (0x04)
// Source: COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_ClusterPositionY_Properties[] = {
    { "Value", 0x00, FIELD_TYPE_FLOAT, 0, true },
};
static const ComponentLayoutDef g_ls_ClusterPositionY_Layout = {
    .componentName = "ls::ClusterPositionYComponent",
    .shortName = "ClusterPositionY",
    .componentTypeIndex = 0,
    .componentSize = 0x04,
    .properties = g_ls_ClusterPositionY_Properties,
    .propertyCount = sizeof(g_ls_ClusterPositionY_Properties) / sizeof(g_ls_ClusterPositionY_Properties[0]),
};

// ls::ClusterPositionZComponent - 4 bytes (0x04)
// Source: COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_ClusterPositionZ_Properties[] = {
    { "Value", 0x00, FIELD_TYPE_FLOAT, 0, true },
};
static const ComponentLayoutDef g_ls_ClusterPositionZ_Layout = {
    .componentName = "ls::ClusterPositionZComponent",
    .shortName = "ClusterPositionZ",
    .componentTypeIndex = 0,
    .componentSize = 0x04,
    .properties = g_ls_ClusterPositionZ_Properties,
    .propertyCount = sizeof(g_ls_ClusterPositionZ_Properties) / sizeof(g_ls_ClusterPositionZ_Properties[0]),
};

// ls::ClusterRadiusComponent - 4 bytes (0x04)
// Source: COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_ClusterRadius_Properties[] = {
    { "Value", 0x00, FIELD_TYPE_FLOAT, 0, true },
};
static const ComponentLayoutDef g_ls_ClusterRadius_Layout = {
    .componentName = "ls::ClusterRadiusComponent",
    .shortName = "ClusterRadius",
    .componentTypeIndex = 0,
    .componentSize = 0x04,
    .properties = g_ls_ClusterRadius_Properties,
    .propertyCount = sizeof(g_ls_ClusterRadius_Properties) / sizeof(g_ls_ClusterRadius_Properties[0]),
};

// ls::VisualStreamHintComponent - 4 bytes (0x04)
// Source: COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_VisualStreamHint_Properties[] = {
    { "Hint", 0x00, FIELD_TYPE_UINT32, 0, true },
};
static const ComponentLayoutDef g_ls_VisualStreamHint_Layout = {
    .componentName = "ls::VisualStreamHintComponent",
    .shortName = "VisualStreamHint",
    .componentTypeIndex = 0,
    .componentSize = 0x04,
    .properties = g_ls_VisualStreamHint_Properties,
    .propertyCount = sizeof(g_ls_VisualStreamHint_Properties) / sizeof(g_ls_VisualStreamHint_Properties[0]),
};

// ls::scene::SceneStageComponent - 4 bytes (0x04)
// Source: COMPONENT_SIZES_LS_MISC.md
static const ComponentPropertyDef g_ls_SceneStage_Properties[] = {
    { "Stage", 0x00, FIELD_TYPE_UINT32, 0, true },
};
static const ComponentLayoutDef g_ls_SceneStage_Layout = {
    .componentName = "ls::scene::SceneStageComponent",
    .shortName = "SceneStage",
    .componentTypeIndex = 0,
    .componentSize = 0x04,
    .properties = g_ls_SceneStage_Properties,
    .propertyCount = sizeof(g_ls_SceneStage_Properties) / sizeof(g_ls_SceneStage_Properties[0]),
};

// ls::AnimationBlueprintComponent - 8 bytes (0x08)
// Source: Visual.h, COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_AnimationBlueprint_Properties[] = {
    { "Instance", 0x00, FIELD_TYPE_PTR, 0, true },
};
static const ComponentLayoutDef g_ls_AnimationBlueprint_Layout = {
    .componentName = "ls::AnimationBlueprintComponent",
    .shortName = "AnimationBlueprint",
    .componentTypeIndex = 0,
    .componentSize = 0x08,
    .properties = g_ls_AnimationBlueprint_Properties,
    .propertyCount = sizeof(g_ls_AnimationBlueprint_Properties) / sizeof(g_ls_AnimationBlueprint_Properties[0]),
};

// ls::AnimationSetComponent - 8 bytes (0x08)
// Source: Visual.h, COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_AnimationSet_Properties[] = {
    { "Entries", 0x00, FIELD_TYPE_PTR, 0, true },
};
static const ComponentLayoutDef g_ls_AnimationSet_Layout = {
    .componentName = "ls::AnimationSetComponent",
    .shortName = "AnimationSet",
    .componentTypeIndex = 0,
    .componentSize = 0x08,
    .properties = g_ls_AnimationSet_Properties,
    .propertyCount = sizeof(g_ls_AnimationSet_Properties) / sizeof(g_ls_AnimationSet_Properties[0]),
};

// ls::ParentEntityComponent - 8 bytes (0x8)
// Source: COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_ParentEntity_Properties[] = {
    { "Parent", 0x00, FIELD_TYPE_ENTITYHANDLE, 0, true },
};
static const ComponentLayoutDef g_ls_ParentEntity_Layout = {
    .componentName = "ls::ParentEntityComponent",
    .shortName = "ParentEntity",
    .componentTypeIndex = 0,
    .componentSize = 0x08,
    .properties = g_ls_ParentEntity_Properties,
    .propertyCount = sizeof(g_ls_ParentEntity_Properties) / sizeof(g_ls_ParentEntity_Properties[0]),
};

// ls::SaveWithComponent - 8 bytes (0x08)
// Source: COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_SaveWith_Properties[] = {
    { "Entity", 0x00, FIELD_TYPE_ENTITYHANDLE, 0, true },
};
static const ComponentLayoutDef g_ls_SaveWith_Layout = {
    .componentName = "ls::SaveWithComponent",
    .shortName = "SaveWith",
    .componentTypeIndex = 0,
    .componentSize = 0x08,
    .properties = g_ls_SaveWith_Properties,
    .propertyCount = sizeof(g_ls_SaveWith_Properties) / sizeof(g_ls_SaveWith_Properties[0]),
};

// ls::level::LevelInstanceTempDestroyedComponent - 8 bytes (0x8)
// Source: Components.h, COMPONENT_SIZES_LS_MISC.md
static const ComponentPropertyDef g_ls_LevelInstanceTempDestroyed_Properties[] = {
    { "Level", 0x00, FIELD_TYPE_ENTITYHANDLE, 0, true },
};
static const ComponentLayoutDef g_ls_LevelInstanceTempDestroyed_Layout = {
    .componentName = "ls::level::LevelInstanceTempDestroyedComponent",
    .shortName = "LevelInstanceTempDestroyed",
    .componentTypeIndex = 0,
    .componentSize = 0x08,
    .properties = g_ls_LevelInstanceTempDestroyed_Properties,
    .propertyCount = sizeof(g_ls_LevelInstanceTempDestroyed_Properties) / sizeof(g_ls_LevelInstanceTempDestroyed_Properties[0]),
};

// ls::anubis::LoadRequestOneFrameComponent - 8 bytes (0x8)
// Source: COMPONENT_SIZES_LS_MISC.md
static const ComponentPropertyDef g_ls_LoadRequestOneFrame_Properties[] = {
    { "Request", 0x00, FIELD_TYPE_PTR, 0, true },
};
static const ComponentLayoutDef g_ls_LoadRequestOneFrame_Layout = {
    .componentName = "ls::anubis::LoadRequestOneFrameComponent",
    .shortName = "LoadRequestOneFrame",
    .componentTypeIndex = 0,
    .componentSize = 0x08,
    .properties = g_ls_LoadRequestOneFrame_Properties,
    .propertyCount = sizeof(g_ls_LoadRequestOneFrame_Properties) / sizeof(g_ls_LoadRequestOneFrame_Properties[0]),
};

// ============================================================================
// Structured Components (16+ bytes)
// ============================================================================

// ls::uuid::Component - 16 bytes (0x10)
// Source: Components.h, COMPONENT_SIZES_LS_MISC.md
static const ComponentPropertyDef g_ls_Uuid_Properties[] = {
    { "EntityUuid", 0x00, FIELD_TYPE_GUID, 0, true },
};
static const ComponentLayoutDef g_ls_Uuid_Layout = {
    .componentName = "ls::uuid::Component",
    .shortName = "Uuid",
    .componentTypeIndex = 0,
    .componentSize = 0x10,
    .properties = g_ls_Uuid_Properties,
    .propertyCount = sizeof(g_ls_Uuid_Properties) / sizeof(g_ls_Uuid_Properties[0]),
};

// ls::LevelComponent - 16 bytes (0x10)
// Source: Components.h, COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_Level_Properties[] = {
    { "field_0", 0x00, FIELD_TYPE_ENTITYHANDLE, 0, true },
    { "LevelName", 0x08, FIELD_TYPE_FIXEDSTRING, 0, true },
};
static const ComponentLayoutDef g_ls_Level_Layout = {
    .componentName = "ls::LevelComponent",
    .shortName = "Level",
    .componentTypeIndex = 0,
    .componentSize = 0x10,
    .properties = g_ls_Level_Properties,
    .propertyCount = sizeof(g_ls_Level_Properties) / sizeof(g_ls_Level_Properties[0]),
};

// ls::VisualComponent - 16 bytes (0x10)
// Source: Visual.h, COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_Visual_Properties[] = {
    { "Visual", 0x00, FIELD_TYPE_PTR, 0, true },
    { "field_8", 0x08, FIELD_TYPE_UINT8, 0, true },
    { "field_9", 0x09, FIELD_TYPE_UINT8, 0, true },
    { "NotClustered", 0x0a, FIELD_TYPE_BOOL, 0, true },
};
static const ComponentLayoutDef g_ls_Visual_Layout = {
    .componentName = "ls::VisualComponent",
    .shortName = "Visual",
    .componentTypeIndex = 0,
    .componentSize = 0x10,
    .properties = g_ls_Visual_Properties,
    .propertyCount = sizeof(g_ls_Visual_Properties) / sizeof(g_ls_Visual_Properties[0]),
};

// ls::trigger::IsInsideOfComponent - 16 bytes (0x10)
// Source: COMPONENT_SIZES_LS_MISC.md
static const ComponentPropertyDef g_ls_IsInsideOf_Properties[] = {
    { "Triggers", 0x00, FIELD_TYPE_ARRAY, 0, true },
};
static const ComponentLayoutDef g_ls_IsInsideOf_Layout = {
    .componentName = "ls::trigger::IsInsideOfComponent",
    .shortName = "IsInsideOf",
    .componentTypeIndex = 0,
    .componentSize = 0x10,
    .properties = g_ls_IsInsideOf_Properties,
    .propertyCount = sizeof(g_ls_IsInsideOf_Properties) / sizeof(g_ls_IsInsideOf_Properties[0]),
};

// ls::animation::DynamicAnimationTagsComponent - 16 bytes (0x10)
// Source: Visual.h, COMPONENT_SIZES_LS_ANIMATION.md
static const ComponentPropertyDef g_ls_DynamicAnimationTags_Properties[] = {
    { "Tags", 0x00, FIELD_TYPE_ARRAY, 0, true },
};
static const ComponentLayoutDef g_ls_DynamicAnimationTags_Layout = {
    .componentName = "ls::animation::DynamicAnimationTagsComponent",
    .shortName = "DynamicAnimationTags",
    .componentTypeIndex = 0,
    .componentSize = 0x10,
    .properties = g_ls_DynamicAnimationTags_Properties,
    .propertyCount = sizeof(g_ls_DynamicAnimationTags_Properties) / sizeof(g_ls_DynamicAnimationTags_Properties[0]),
};

// ls::animation::TemplateAnimationSetOverrideComponent - 16 bytes (0x10)
// Source: Visual.h, COMPONENT_SIZES_LS_ANIMATION.md
static const ComponentPropertyDef g_ls_TemplateAnimationSetOverride_Properties[] = {
    { "Overrides", 0x00, FIELD_TYPE_ARRAY, 0, true },
};
static const ComponentLayoutDef g_ls_TemplateAnimationSetOverride_Layout = {
    .componentName = "ls::animation::TemplateAnimationSetOverrideComponent",
    .shortName = "TemplateAnimationSetOverride",
    .componentTypeIndex = 0,
    .componentSize = 0x10,
    .properties = g_ls_TemplateAnimationSetOverride_Properties,
    .propertyCount = sizeof(g_ls_TemplateAnimationSetOverride_Properties) / sizeof(g_ls_TemplateAnimationSetOverride_Properties[0]),
};

// ls::animation::LoadAnimationSetGameplayRequestOneFrameComponent - 16 bytes (0x10)
// Source: Visual.h, COMPONENT_SIZES_LS_ANIMATION.md
static const ComponentPropertyDef g_ls_LoadAnimationSetGameplayRequestOneFrame_Properties[] = {
    { "Animations", 0x00, FIELD_TYPE_ARRAY, 0, true },
};
static const ComponentLayoutDef g_ls_LoadAnimationSetGameplayRequestOneFrame_Layout = {
    .componentName = "ls::animation::LoadAnimationSetGameplayRequestOneFrameComponent",
    .shortName = "LoadAnimationSetGameplayRequestOneFrame",
    .componentTypeIndex = 0,
    .componentSize = 0x10,
    .properties = g_ls_LoadAnimationSetGameplayRequestOneFrame_Properties,
    .propertyCount = sizeof(g_ls_LoadAnimationSetGameplayRequestOneFrame_Properties) / sizeof(g_ls_LoadAnimationSetGameplayRequestOneFrame_Properties[0]),
};

// ls::PhysicsComponent - 24 bytes (0x18)
// Source: Visual.h, COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_Physics_Properties[] = {
    { "Physics", 0x00, FIELD_TYPE_PTR, 0, true },
    { "PhysicsGroup", 0x08, FIELD_TYPE_UINT32, 0, true },
    { "CollidesWith", 0x0c, FIELD_TYPE_UINT32, 0, true },
    { "ExtraFlags", 0x10, FIELD_TYPE_UINT32, 0, true },
    { "HasPhysics", 0x14, FIELD_TYPE_BOOL, 0, true },
    { "field_15", 0x15, FIELD_TYPE_UINT8, 0, true },
    { "IsClustered", 0x16, FIELD_TYPE_BOOL, 0, true },
};
static const ComponentLayoutDef g_ls_Physics_Layout = {
    .componentName = "ls::PhysicsComponent",
    .shortName = "Physics",
    .componentTypeIndex = 0,
    .componentSize = 0x18,
    .properties = g_ls_Physics_Properties,
    .propertyCount = sizeof(g_ls_Physics_Properties) / sizeof(g_ls_Physics_Properties[0]),
};

// ls::animation::RemoveAnimationSetsGameplayRequestOneFrameComponent - 48 bytes (0x30)
// Source: Visual.h, COMPONENT_SIZES_LS_ANIMATION.md
static const ComponentPropertyDef g_ls_RemoveAnimationSetsGameplayRequestOneFrame_Properties[] = {
    { "AnimationSets", 0x00, FIELD_TYPE_HASHSET, 0, true },
};
static const ComponentLayoutDef g_ls_RemoveAnimationSetsGameplayRequestOneFrame_Layout = {
    .componentName = "ls::animation::RemoveAnimationSetsGameplayRequestOneFrameComponent",
    .shortName = "RemoveAnimationSetsGameplayRequestOneFrame",
    .componentTypeIndex = 0,
    .componentSize = 0x30,
    .properties = g_ls_RemoveAnimationSetsGameplayRequestOneFrame_Properties,
    .propertyCount = sizeof(g_ls_RemoveAnimationSetsGameplayRequestOneFrame_Properties) / sizeof(g_ls_RemoveAnimationSetsGameplayRequestOneFrame_Properties[0]),
};

// ls::TransformComponent - 40 bytes (0x28)
// Source: Components.h, COMPONENT_SIZES_LS_CORE.md
// Note: Transform struct is typically mat4x4 (position + rotation matrix)
static const ComponentPropertyDef g_ls_Transform_Properties[] = {
    { "Transform", 0x00, FIELD_TYPE_TRANSFORM, 0, true },
};
static const ComponentLayoutDef g_ls_Transform_Layout = {
    .componentName = "ls::TransformComponent",
    .shortName = "Transform",
    .componentTypeIndex = 0,
    .componentSize = 0x28,
    .properties = g_ls_Transform_Properties,
    .propertyCount = sizeof(g_ls_Transform_Properties) / sizeof(g_ls_Transform_Properties[0]),
};

// ls::uuid::ToHandleMappingComponent - 64 bytes (0x40)
// Source: Components.h, COMPONENT_SIZES_LS_MISC.md
static const ComponentPropertyDef g_ls_UuidToHandleMapping_Properties[] = {
    { "Mappings", 0x00, FIELD_TYPE_HASHMAP, 0, true },
};
static const ComponentLayoutDef g_ls_UuidToHandleMapping_Layout = {
    .componentName = "ls::uuid::ToHandleMappingComponent",
    .shortName = "UuidToHandleMapping",
    .componentTypeIndex = 0,
    .componentSize = 0x40,
    .properties = g_ls_UuidToHandleMapping_Properties,
    .propertyCount = sizeof(g_ls_UuidToHandleMapping_Properties) / sizeof(g_ls_UuidToHandleMapping_Properties[0]),
};

// ls::LevelInstanceComponent - 64 bytes (0x40)
// Source: Components.h, COMPONENT_SIZES_LS_CORE.md
static const ComponentPropertyDef g_ls_LevelInstance_Properties[] = {
    { "LevelInstanceID", 0x00, FIELD_TYPE_FIXEDSTRING, 0, true },
    { "LevelName", 0x04, FIELD_TYPE_FIXEDSTRING, 0, true },
    { "LevelInstanceTemplate", 0x08, FIELD_TYPE_FIXEDSTRING, 0, true },
    { "LevelType", 0x0c, FIELD_TYPE_UINT8, 0, true },
    { "Active", 0x0d, FIELD_TYPE_BOOL, 0, true },
    { "Platform", 0x0e, FIELD_TYPE_BOOL, 0, true },
    { "MovingPlatform", 0x0f, FIELD_TYPE_BOOL, 0, true },
    { "DynamicLayer", 0x10, FIELD_TYPE_BOOL, 0, true },
    { "NeedsPhysics", 0x11, FIELD_TYPE_BOOL, 0, true },
};
static const ComponentLayoutDef g_ls_LevelInstance_Layout = {
    .componentName = "ls::LevelInstanceComponent",
    .shortName = "LevelInstance",
    .componentTypeIndex = 0,
    .componentSize = 0x40,
    .properties = g_ls_LevelInstance_Properties,
    .propertyCount = sizeof(g_ls_LevelInstance_Properties) / sizeof(g_ls_LevelInstance_Properties[0]),
};
